language : cpp
compiler:
    - gcc

before_install:
    # g++4.8.1
    - if [ "$CXX" == "g++" ]; then sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test; fi

    - sudo apt-get update -qq

install:
    # g++4.8.1
    - if [ "$CXX" = "g++" ]; then sudo apt-get install -qq g++-4.8; fi
    - if [ "$CXX" = "g++" ]; then export CXX="g++-4.8"; fi

    - sudo apt-get install cmake
    - sudo apt-get install libeigen3-dev
    - sudo apt-get install libgtest-dev
    - "cd /usr/src/gtest && sudo cmake . && sudo cmake --build . && ls && sudo mv libg* /usr/lib/ ; cd -"

before_script:
    - mkdir build
    - cd build

script: cmake .. && make
